version: "3.9"
services:
  python:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh
      - ~/.aws:/root/.aws
    # keep container running
    command: /bin/sh -c "while :; do sleep 10; done"
    depends_on:
      - localstack
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=s3
    volumes:
      - ./.devcontainer/localstack:/tmp/localstack
